### ISSUE TITLE
Allow modifying method invocation return values

### ISSUE THREAD

**Issue by kzu** [devlooped/avatar#61]
It would be useful to be able to modify the returned values from a call to the base method implementation or the subsequent behaviors in the pipeline before returning to caller.

Currently, `IMethodReturn` has no public implementation and no mutating members that can be used for that, so it's pretty much forbidden (unless you implement the interface yourself).

We could either make the internal `MethodReturn` implementation public (like we do for `MethodInvocation` itself and/or add mutating methods like `WithArguments`, `WithReturnValue` and `WithException`. Since almost all our interface implementations are public, maybe that's the simplest approach here too?

From feedback by @stakx in #56

**Comment by kzu** [comment]
@stakx for feedback 👍

**Comment by stakx** [comment]
I originally voted towards `With...` methods, but didn't consider that some implementation types are already public... so yes, making `MethodReturn` public too is perhaps indeed easiest... esp. if user implementations would end up being near identical anyway.

I was wondering whether it could be implemented as a `record`? That might give us `with` syntax for free...?

**Comment by kzu** [comment]
Yeah, making it a record sounds good. I'll see how that looks 👍. Will need [IsExternalInit](https://til.cazzulino.com/dotnet/use-c-9-records-in-non-net5.0-projects) to keep it NS2, but it should just work...

**Comment by kzu** [comment]
Works like a charm :)

![image](https://user-images.githubusercontent.com/169707/102814398-55072e00-43a9-11eb-97e2-84dc92e4b941.png)
